# Generated by Django 4.1.6 on 2023-12-20 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='follow_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_being_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follows',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_user_follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follows_me',
            name='follows_me_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follows_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follows_me',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='im_being_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
