# Generated by Django 4.1.6 on 2023-12-24 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_is_liked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='follows_me',
        ),
    ]
